apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-deployment.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ include "helm-deployment.name" . }}
    instance: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    name: {{ include "helm-deployment.name" . }}
    instance: {{ .Release.Name }}

